DROP USER tomato CASCADE;
CREATE USER tomato IDENTIFIED BY javabuu;
GRANT DBA, CONNECT, RESOURCE TO tomato;


-- 테스트하려고 회원 테이블에서 주소 외래키로 받는 제약조건 NOTNULL 에서 NULL 로 변경
ALTER TABLE MEMBERS MODIFY CODE NULL;
ALTER TABLE MEMBERS MODIFY DONG_ID NULL;